In [5]:
 import numpy as np
x=np.array([1,23,5,56,7,6])
print(x)
print(type(x))

[ 1 23  5 56  7  6]
<class 'numpy.ndarray'>


In [6]:
y=[1,23,5,56,7,6]
print(type(y))

<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

472 ns ± 37.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
import numpy as np
%timeit

In [2]:

import numpy as np
x=[1,2,3,4,5]
y=np.array(x)
print(type(y))

<class 'numpy.ndarray'>


# for loop er mardhome list input and nympy array te conversion

In [5]:
# for loop er mardhome list input and nympy array te conversion
l=[]
for i in range(1,5):
    x=int(input("enter"))
    l.append(x)
    
print(l)
print(np.array(l))
    
    
    

enter 5544
enter 445
enter 44
enter 4


[5544, 445, 44, 4]
[5544  445   44    4]


In [43]:
#any  dimension in arrays create
arr2=np.array([[23,45,43],[43,22,45]])
print(arr2)
print(arr2.ndim)

[[23 45 43]
 [43 22 45]]
2


In [16]:
    arr3=np.array([[[23,45,43],[43,22,45],[34,54,33]]])
print(arr3)
print(arr3.ndim)

[[[23 45 43]
  [43 22 45]
  [34 54 33]]]
3


In [17]:
arr2=np.array([[23,45,43],[43,22,45]],ndmin=10)
print(arr2)
print(arr2.ndim)

[[[[[[[[[[23 45 43]
         [43 22 45]]]]]]]]]]
10


In [ ]:
l=[]
for i in range(1,5):
    x=int(input("enter"))
    l.append(x)
    
print(l)

# ar_zero create

In [23]:

ar_zero=np.zeros(((3,2,5)))
print(ar_zero)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


# ar_empty create

In [27]:
# ar_ones create
ar_ones=np.ones((3,6))
print(ar_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [29]:
ar_empty=np.empty(4)
print(ar_empty)

[2.739e-320 2.199e-321 2.174e-322 1.976e-323]


In [30]:
# ar_range 
ar_range=np.arange(5)
print(ar_range)

[0 1 2 3 4]


# diagonal element one 
ar_diagonal=np.eye(3,4)
print(ar_diagonal)

In [34]:
ar_diagonal=np.eye(4)
print(ar_diagonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# linspace

In [42]:
ar_lin=np.linspace(0,20,5)

print(ar_lin)

[ 0.  5. 10. 15. 20.]


# random functon()

In [45]:
import numpy as np
var=np.random.rand(5)
print(var)

[0.37669248 0.77249205 0.01918857 0.77722437 0.89417832]


In [46]:
import numpy as np
var=np.random.rand(4,5)
print(var)

[[0.67518301 0.73591804 0.86691804 0.00753199 0.42454665]
 [0.48690064 0.71333235 0.8837057  0.49348062 0.67197233]
 [0.54569361 0.79639182 0.93700826 0.97077128 0.69908304]
 [0.46711795 0.07525735 0.62670902 0.73828725 0.20460148]]


In [48]:
import numpy as np
var=np.random.randn(5)
print(var)

[-2.63268616 -0.86041239  1.72145099  0.64669364 -2.36670339]


In [49]:
 import numpy as np
var=np.random.ranf(5)
print(var)

[0.5073955  0.33839266 0.32201926 0.95068174 0.63835824]


In [51]:
import numpy as np
var=np.random.randint(5,23,7)
print(var)

[22 18 10 18 14 13 13]


# numpy array data types

In [53]:
var=np.array([2,3,45,6])
print("data type : ",var.dtype)

data type :  int64


In [54]:
var=np.array([2.4,3.5,45.5,6.4])
print("data type : ",var.dtype)

data type :  float64


In [55]:
var=np.array(["a",3.5,45.5,"6.4"])
print("data type : ",var.dtype)

data type :  <U32


In [56]:
var=np.array(['g','h','g','t','e','r'])
print("data type : ",var.dtype)

data type :  <U1


In [58]:
var=np.array([2,3,5,6],dtype=np.int8)
print("data type : ",var.dtype)

data type :  int8


In [66]:
var=np.array([2,3,5,6])
new=np.float32(var)
print("data type : ",var.dtype)
print("data type : " ,new.dtype)

data type :  int64
data type :  float32


In [67]:
var=np.array([2,3,5,6],dtype=np.int32)
print("data type : ",var.dtype)

data type :  int32


In [68]:
var=np.array([2,3,5,6],np.float32)

print("data type : ",var.dtype)
print("data type : " ,new.dtype)

data type :  float32
data type :  float32


 # arithmetic operation in numpy arrays 

In [1]:
 import numpy as np
var=np.array([3,4,5,6,7])
var= var+3
print(var)

[ 6  7  8  9 10]


In [9]:
 import numpy as np
var=np.array([3,4,5,6,7])
var2=np.array([3,4,5,6,7])

result=np.add(var,var2)
print(result)
var= var+var2
print(var)

[ 6  8 10 12 14]
[ 6  8 10 12 14]


In [3]:
import numpy as np
var=np.array([3,4,5,6,7])
var= var*3
print(var)

[ 9 12 15 18 21]


In [6]:
import numpy as np
var=np.array([3,4,5,6,7])
var= var/3
print(var)

[1.         1.33333333 1.66666667 2.         2.33333333]


In [ ]:
import numpy as np
var=np.array([3,4,5,6,7])
var= var%3
print(var)

In [12]:
import numpy as np
var=np.array([3,4,5,6,7])
var= np.pow(var,2)
print(var)

[ 9 16 25 36 49]


In [16]:
import numpy as np
var=np.array([3.4,4.5,5.7,6.3,7.6])
var= np.reciprocal(var)
print(var)

[0.29411765 0.22222222 0.1754386  0.15873016 0.13157895]


# arithmetic function in numpy

In [18]:
import numpy as np
var=np.array([1,2,3,45,5,6,7])
print("min :",np.min(var))
print("max :",np.max(var))


min : 1
max : 45


In [22]:
import numpy as np
var=np.array([1,2,3,45,5,6,7])
print("min :",np.min(var),np.argmin(var))
print("max :",np.max(var),np.argmax(var))


min : 1 0
max : 45 3


In [27]:
var1=np.array([[3,4,5],[5,1,7]])
print(np.min(var1))

1


In [26]:
var1=np.array([[3,4,5],[5,1,7]])
print(np.min(var1,axis=0))

[3 1 5]


In [30]:
var1=np.array([[3,4,5],[5,1,7]])

print(np.sqrt(var1))

[[1.73205081 2.         2.23606798]
 [2.23606798 1.         2.64575131]]


In [33]:
var2=np.array([1,2,3,4])
print(np.sin(var2))
print(np.cos(var2))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [36]:
var3=np.array([1,2,34,5])

print(np.cumsum(var3))

[ 1  3 37 42]


# learn about shape and reshaping in numpy arrays

In [2]:
 import numpy as np
var =np.array([[1,2],[3,4]])
print(var)
print()
print(var.shape)

[[1 2]
 [3 4]]

(2, 2)


In [3]:
 import numpy as np
var =np.array([[1,2,4],[3,4,7]])
print(var)
print()
print(var.shape)

[[1 2 4]
 [3 4 7]]

(2, 3)


In [4]:
 import numpy as np
var =np.array([[1,2],[3,4]],ndmin=5)
print(var)
print()
print(var.shape)

[[[[[1 2]
    [3 4]]]]]

(1, 1, 1, 2, 2)


In [20]:
 import numpy as np
var =np.array([ 1,3,37,42,7,9])
print(var)
print()
x=var.reshape(3,2)
print(x.ndim)


print(x)

[ 1  3 37 42  7  9]

2
[[ 1  3]
 [37 42]
 [ 7  9]]


# learn broadcasting in numpy arrays

In [23]:
# dimension same then the working brodcasting

In [22]:
import numpy as np
var1=np.array([1,2,6])
var2=np.array([1,2,3]) 
print(var1+var2)

[2 4 9]


# indexing and slicing in numpy arrays

In [26]:
import numpy as pd
var=np.array([9,8,7,6,5])
#             0,1,2,3,4 
print(var[0])
print(var[-1])
print(var[-5])

9
5
9


In [30]:
var1=np.array([[1,44,55],[4,5,73]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])

[[ 1 44 55]
 [ 4  5 73]]
2

55


In [34]:
var2=np.array([[1,44,55],[4,5,73]],ndmin=3)
print(var2)
print(var2.ndim)
print()
print(var2[0,0,1])

[[[ 1 44 55]
  [ 4  5 73]]]
3

44


In [35]:
var2=np.array([[1,44,55],[4,5,73]],ndmin=3)
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[ 1 44 55]
  [ 4  5 73]]]
3

5


# slicing numpy arrays

In [45]:
 import numpy as np
var=np.array([3,5,6,7,8])
#             0,1,2,3,4
print(var)
print(var[1:3])
print(var[1:])
print(var[:5])
print(var[::2])
print(var[1:4:2])

[3 5 6 7 8]
[5 6]
[5 6 7 8]
[3 5 6 7 8]
[3 6 8]
[5 7]


In [48]:
var1=np.array([[1,2,3,4,5],[3,45,3,2,3],[2,3,4,5,5]])
print(var1[1,1:])

[45  3  2  3]


# iterating numpuy arrays

In [50]:
import numpy as np
var=np.array([9,8,7,6,5,4,3,3,2])
print()
for i in var:
    print(i)


9
8
7
6
5
4
3
3
2


In [56]:
var1=np.array([[1,3,4,5,6],[1,2,3,4,5]])
print(var1)
print()
for j in var1:
    print(j)
print()


for k in var1:
    for l in k:
        print(l)

[[1 3 4 5 6]
 [1 2 3 4 5]]

[1 3 4 5 6]
[1 2 3 4 5]

1
3
4
5
6
1
2
3
4
5


In [57]:
var1=np.array([[1,3,4,5,6],[1,2,3,4,5]])
print(var1)
print()
for j in np.nditer(var):
    print(j)

    

[[1 3 4 5 6]
 [1 2 3 4 5]]

9
8
7
6
5
4
3
3
2


In [59]:
var1=np.array([[1,3,4,5,6],[1,2,3,4,5]])
print(var1)
print()
for i,d in np.ndenumerate(var1):
    print(i,d)


[[1 3 4 5 6]
 [1 2 3 4 5]]

(0, 0) 1
(0, 1) 3
(0, 2) 4
(0, 3) 5
(0, 4) 6
(1, 0) 1
(1, 1) 2
(1, 2) 3
(1, 3) 4
(1, 4) 5


# copy vs view in numpy arrays

In [63]:
import numpy as np
var=np.array([2,4,5,6])

co=var.copy()
var[2]=34
print("var : ", var)
print("var:",co)


var :  [ 2  4 34  6]
var: [2 4 5 6]


In [64]:
import numpy as np
var=np.array([2,4,5,6])
vie=var.view()
var[1]=67
print("var : ", var)
print("var:",vie)

var :  [ 2 67  5  6]
var: [ 2 67  5  6]


# joining and split in  Numpy arrarys

In [65]:
   import numpy as np
var=np.array([12,2,3,4,5,6])
var1=np.array([33,44,5,6,7,8])
ar=np.concatenate((var,var1))
print(ar)  

[12  2  3  4  5  6 33 44  5  6  7  8]


In [71]:
   import numpy as np
vr=np.array([[12,3],
             [4,6]])
var1=np.array([[33,44],
               [5,6,]])
ar_new=np.concatenate((vr,var1),axis=0)
print(ar_new)

[[12  3]
 [ 4  6]
 [33 44]
 [ 5  6]]


In [72]:
   import numpy as np
vr=np.array([[12,3],
             [4,6]])
var1=np.array([[33,44],
               [5,6,]])
ar_new=np.concatenate((vr,var1),axis=1)
print(ar_new)

[[12  3 33 44]
 [ 4  6  5  6]]


In [76]:
 import numpy as np
vr=np.array([[12,3],
             [4,6]]) 
var1=np.array([[33,44],
               [5,6,]])
ar_ne=np.stack((vr,var1),axis=1)
print(ar_ne)

[[[12  3]
  [33 44]]

 [[ 4  6]
  [ 5  6]]]


In [80]:
import numpy as np
vr=np.array([[12,3],
             [4,6]]) 
var1=np.array([[33,44],
               [5,6,]])
ar_ne=np.vstack((vr,var1))
print(ar_ne)

[[12  3]
 [ 4  6]
 [33 44]
 [ 5  6]]


In [82]:
import numpy as np
vr=np.array([[12,3],
             [4,6]]) 
var1=np.array([[33,44],
               [5,6,]])
ar_ne=np.hstack((vr,var1))
print(ar_ne)

[[12  3 33 44]
 [ 4  6  5  6]]


# split array

In [85]:
import numpy as np
var=np.array([[1,2],[45,5]])
print(var)
ar=np.array_split(var,2)
print(ar)

[[ 1  2]
 [45  5]]
[array([[1, 2]]), array([[45,  5]])]


# numpy array function

In [86]:
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,3,2,2,345,334,56,2,2])
x=np.where(var==2)
print(x)

(array([ 1,  9, 10, 14, 15]),)


In [93]:
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,3,2,2,345,334,56,2,2])
x=np.where(var%2==0)
print(x)

(array([ 1,  3,  5,  7,  9, 10, 12, 13, 14, 15]),)


In [99]:
import numpy as np
var1=np.array([1,2,3,4,5,6,7,8,3,2,2,345,334,56])
x1=np.searchsorted(var1,23,side="right")
print(x1)

11


In [101]:
import numpy as np
var1=np.array([1,2,3,4,5,6,7,8,3,2,2,345,334,56])
x1=np.searchsorted(var1,23,side="left")
print(x1)

11


In [108]:
import numpy as np
var1=np.array([1,2,3,45,5,6,447,8,3,345,334,56])
x1=np.searchsorted(var1,[3,4,64],side="right")
print(x1)

[3 3 9]


# sort

In [109]:
var1=np.array([1,2,3,45,5,6,447,8,3,345,334,56])
print(np.sort(var1))

[  1   2   3   3   5   6   8  45  56 334 345 447]


In [110]:
var1=np.array(['d','t','y','g','c','a','k','s'])
print(np.sort(var1))

['a' 'c' 'd' 'g' 'k' 's' 't' 'y']


In [111]:
var1=np.array([[1,2,3],[45,5,6],[447,8,3],[345,334,56]])
print(np.sort(var1))

[[  1   2   3]
 [  5   6  45]
 [  3   8 447]
 [ 56 334 345]]


In [7]:
import numpy as np
marks=np.array([30,55,70,25,90])
condition=marks>40
print(condition)
x=marks[[False,True,True,False,True]]
print(x)


[False  True  True False  True]
[55 70 90]


# arithmetic functions

In [11]:
import numpy as np
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 5 2 1 4]


In [14]:
import numpy as np
var1=np.array([1,2,3,4,5,2,3,5])
x=np.unique(var1,return_index=True)
print(x)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4]))


In [22]:
var1=np.array([1,2,3,4,5,2,3,5])
y=np.resize(var,(2,4))
print()
print(y)
print(var1.flatten())
print(var)
r=var1.ravel()
print(r)


[[3 5 2 1]
 [4 3 5 2]]
[1 2 3 4 5 2 3 5]
[3 5 2 1 4]
[1 2 3 4 5 2 3 5]


# insert and delete function

In [25]:
import numpy as np
var=np.array([1,3,45,5,6,7])
v=np.insert(var,(4,0),(233,34.4))
print(v)

[ 34   1   3  45   5 233   6   7]


In [37]:
import numpy as np
var=np.array([[1,3,45],[5,6,7]])
v=np.insert(var,0,[44,4,6],axis=0)
print(v)
c1=np.append(var,[[33,44,550],[34,55,66]],axis=0)
print()
print(c1)

[[44  4  6]
 [ 1  3 45]
 [ 5  6  7]]

[[  1   3  45]
 [  5   6   7]
 [ 33  44 550]
 [ 34  55  66]]


In [40]:
import numpy as np
var=np.array([1,3,45,5,6,7])
print(var)
d=np.delete(var,2)
print(d)

[ 1  3 45  5  6  7]
[1 3 5 6 7]


# matrix 

In [44]:
import numpy as np
var=np.matrix([[1,2,3],[1,2,3]])
var1=np.matrix([[1,2,3],[1,2,3]])

print(type(var))
print(var+var1)


<class 'numpy.matrix'>
[[2 4 6]
 [2 4 6]]


In [42]:
import numpy as np
var=np.array([[1,2,3],[1,2,3]])
print(type(var))

<class 'numpy.ndarray'>


In [54]:
import numpy as np
var=np.matrix([[1,2,3],[1,2,3]])
var1=np.matrix([[1,2,54],[1,5,3],[233,43,22]])

print(type(var))
print(var*var1)
print()
print(var.dot(var1))

<class 'numpy.matrix'>
[[702 141 252]
 [702 141 252]]



NameError: name 'var2' is not defined

In [66]:
import numpy as np
var=np.matrix([[1,45,3],[1,45,3]])
var1=np.matrix([[1,2,54],[1,5,66],[2,345,5]])

print(type(var))
print(var*var1)
print()
print(var.dot(var1))
print()
print(np.transpose(var))
print()
print(np.swapaxes(var))


<class 'numpy.matrix'>
[[  52 1262 3039]
 [  52 1262 3039]]

[[  52 1262 3039]
 [  52 1262 3039]]

[[ 1  1]
 [45 45]
 [ 3  3]]



TypeError: swapaxes() missing 2 required positional arguments: 'axis1' and 'axis2'

In [78]:
import numpy as np

var1=np.matrix([[1,2,54],[1,5,66],[2,345,5]])
print(np.linalg.inv(var1))
print()
print(np.linalg.matrix_power(var1,2))
print()
print(np.linalg.det(var1))

[[ 5.16814360e+00 -4.23085662e+00  3.13565099e-02]
 [-2.88570779e-02  2.34037719e-02  2.72665303e-03]
 [-7.61190638e-02  7.74823904e-02 -6.81663258e-04]]

[[  111 18642   456]
 [  138 22797   714]
 [  357  3454 22903]]

-4401.000000000005
